### ISSUE TITLE
Asset generator breaks on meeting a not image file in image dir

### ISSUE THREAD

**Issue by andreiShevelevDC** [arsenmazmanyan/phaser3-starting-template#1]
In my case it's ".DS_Store".
MacOS recreates this file every time you open images dir in the Finder

![Screen Shot 2022-07-12 at 14 06 53](https://user-images.githubusercontent.com/105287426/178470158-46b4a004-508c-4fbe-a14c-b422099a985f.png)

I would suggest to explicitly add all supported image extensions to the filter, or at least most common ones like (png, jpg, jpeg, bmp, gif).
This way the template will also not break on any non-image file got in the image directory.

P.S. On Windows versions 2000, XP, Vista there is also a hidden thumbnail cache file "Thumbs.db" that is created automatically when a folder with images are opened in Explorer.

**Comment by arsenmazmanyan** [comment]
https://github.com/arsenmazmanyan/phaser3-starting-template/commit/20cec77fb5f9a77a0bc04dc40193bf52ee15124a

solved
